# Configuration for Pendulum PINN Training

# --- File Paths ---
paths:
  model_save: "results/pendulum_model.pt"
  loss_plot: "results/model/training_loss.png"

# --- Problem Definition ---
problem:
  discretization_points: 2000  # Increased for better physics resolution
  initial_condition_weight: 10000.0  # Much higher weight for initial conditions
  # Note: output_variables ['theta', 'omega'] defined in Pendulum class
  # Note: domain {'t': [0.0, 1.0]} defined in Pendulum class

# --- Model Architecture (ResNet specific) ---
model:
  type: "ResNet"
  hidden_dim: 32  # Reduced size
  num_blocks: 2   # Fewer blocks
  # input_dim: 1 # Determined by problem.input_variables in train_pina.py
  # output_dim: 2 # Determined by problem.output_variables in train_pina.py

# --- Optimizer Configuration ---
optimizer:
  # class_name: "Adam" # Implicitly torch.optim.Adam in current setup
  lr: 0.001  # Lower learning rate
  weight_decay: 1e-5  # Slightly higher weight decay

# --- Scheduler Configuration ---
scheduler:
  class_name: "ReduceLROnPlateau"
  monitor: "train_loss"
  mode: "min"
  factor: 0.5
  patience: 100  # More patience
  threshold: 0.0001
  threshold_mode: "rel"
  cooldown: 10  # Added cooldown
  min_lr: 1e-6

# --- Trainer Configuration ---
trainer:
  max_epochs: 20000  # More epochs
  batch_size: 64    # Larger batch size
  gradient_clip_val: 1.0
  enable_model_summary: false

# --- Simulation Parameters (Moved from constants.py) ---
# Note: Physical constants (G, L) and initial conditions (theta0, omega0)
# remain in constants.py. Scaling factors also remain there as they
# depend on initial conditions.
simulation:
  time: 5.0 # Physical simulation time (used in equations) 